### ISSUE TITLE
not compatible with the current version of VSCode (version 1.65.0).

### ISSUE THREAD

**Issue by kin9-0rz** [massCodeIO/assistant-vscode#5]
```
ERR Can't install 'antonreshetov.masscode-assistant' extension because it is not compatible with the current version of Visual Studio Code (version 1.65.0).: Incompatible: Can't install 'antonreshetov.masscode-assistant' extension because it is not compatible with the current version of Visual Studio Code (version 1.65.0).
    at U.checkAndGetCompatibleVersion (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:12147)
    at async U.installFromGallery (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:3200)
```

**Comment by antonreshetov** [comment]
Because min version is 1.66.0 https://github.com/massCodeIO/assistant-vscode/blob/master/package.json#L7
